# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst

sudo: required
dist: xenial
services:
  - docker
language: generic 
compiler:
  - gcc
notifications:
  email:
    recipients:
      - isaac.saito@plusonerobotics.com

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
# - git clone -v --progress https://github.com/doronhi/realsense.git  # This is Done automatically by TravisCI
before_install:
  - sudo ./.install_dependency.sh
    # download data:
  - bag_filename="http://realsense-hw-public.s3.amazonaws.com/rs-tests/TestData/outdoors.bag";
  - wget $bag_filename -P "records/"
env:
  matrix:
    - ROS_DISTRO="kinetic"   ROS_REPO=ros/main
    - ROS_DISTRO="kinetic"   PRERELEASE=true
    - ROS_DISTRO="melodic"   ROS_REPO=ros/main
    - ROS_DISTRO="melodic"   PRERELEASE=true
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
  # Run test
  - python src/realsense/realsense2_camera/scripts/rs2_test.py --all
 